# Generated by Django 2.1.4 on 2018-12-06 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palestrante', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palestrante',
            name='cargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='palestrante',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='palestrante',
            name='palestrante',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='palestrante',
            name='resumo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='palestrante',
            name='telefone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='palestrante',
            name='tema',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
