# Generated by Django 2.1.4 on 2018-12-06 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palestrante', '0002_auto_20181206_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palestrante',
            name='resumo',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
