# Generated by Django 2.1.4 on 2018-12-06 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palestrante', '0003_auto_20181206_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palestrante',
            name='resumo',
            field=models.TextField(),
        ),
    ]
