# Generated by Django 2.1.4 on 2018-12-06 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palestrante', '0004_auto_20181206_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palestrante',
            name='resumo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
