# Generated by Django 2.1.4 on 2018-12-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palestrante', '0005_auto_20181206_0103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='palestrante',
            options={'ordering': ['palestrante'], 'verbose_name': 'palestrante', 'verbose_name_plural': 'palestrantes'},
        ),
        migrations.AlterField(
            model_name='palestrante',
            name='cargo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
